fun main() {
    println("Hello to Advent of Code 2022, Khatharsis edition !")
    Day1().solve()
    Day2().solve()
    Day2Alternative().solve()
    Day3().solve()
//    Day24_2020().solve()
    Day4().solve()
    Day5().solve()
    Day6().solve()
    Day7().solve()
    Day8().solve()
    Day9().solve()
    Day10().solve()
    Day11().solve()
    Day12().solve()
    Day13().solve()
    Day14().solve()
    Day15().solve()
}